### DISCUSSION TITLE
Testing shared danger rules

### DISCUSSION THREAD

**Discussion by glensc** [danger/danger-js#1250] [General]
So, I have a project, which I deliver as docker image to be run in gitlab pipeline with bundled dangerfile in the image.

KInd of like:

```yaml

danger-ci:
  stage: test
  image: $DANGER_IMAGE
  dependencies: []
  needs: []
  variables:
    DANGER_GITLAB_HOST: $CI_SERVER_HOST
    DANGER_GITLAB_API_BASE_URL: $CI_API_V4_URL
    DANGER_VERBOSE: 1
    DANGER_DANGERFILE: /app/dangerfile.js
  script:
    - export CI_MERGE_REQUEST_IID=${CI_OPEN_MERGE_REQUESTS#*!}
    - echo "Using $DANGER_DANGERFILE on merge request $CI_MERGE_REQUEST_IID"
    - danger-ci --dangerfile $DANGER_DANGERFILE --failOnErrors
 ```
that all works fine.

----
 
now to test the new changes in merge request, an inside same project I just override DANGER_DANGERFILE:

```yml
  DANGER_DANGERFILE: $CI_PROJECT_DIR/dangerfile.ts
```

that is also fine

----

But any ideas on how to run the dangerfile.ts (and its dependencies) to third-party project?

Can danger.js load files over http? or git repo? or gitlab api?
