### DISCUSSION TITLE
Self-hosted gitlab HTTPError: Response code 404 (Not Found)

### DISCUSSION THREAD

**Discussion by emmesbef** [danger/danger-js#1322] [Q&A]
Hi,

i do some testing on my private hosted gitlab with danger@11.1.3. I set up the personal accestoken as repo variable, i also checked spelling errors and checked if the variable is set. The ``DANGER_GITLAB_HOST`` variable is also set. But i do get HTTPError 404(Not Found)

edit:

i did test the same setup on gitlab.com and also with just the Accesstoken, no HTTPError
the the domain is replaced with placeholder for privacy reasons

```
Error:  HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1664715181960,
    socket: 1664715181963,
    lookup: 166[47](https://<sub>.<domainName>.<tld>/<user>/<repo>/-/jobs/247#L47)15181964,
    connect: 1664715181966,
    secureConnect: 1664715181971,
    upload: 1664715181972,
    response: 166471[51](https://<sub>.<domainName>.<tld>/<user>/<repo>/-/jobs/247#L51)81992,
    end: 1664715181994,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 1,
      tcp: 2,
      tls: 5,
      request: 1,
      firstByte: 20,
      download: 2,
      total: 34
    }
  },
  description: undefined
}
```
here the yaml

```yaml
default: 
  image: node:16.13.1
stages:
  - check
variables:
  DANGER_GITLAB_HOST: 'https://<sub>.<domainName>.<tld>'
  DANGERFILE: './dangerfile.ts'
danger-check:
  only:
    - merge_requests
  image: node:16.13.1
  stage: check
  script:  
    - yarn global add danger --skip-integrity-check
    - echo "run ci command..."
    - danger ci --dangerfile=$DANGERFILE -f -v
```

The local test with ``danger pr https://<sub>.<domainName>.<tld>/<user>/<repoName>/merge_request/<mergeid>`` ends up in the same error.

And here my dangerfile

```typescript
const gitlab = danger.gitlab;

if(!gitlab.api){
    fail("no access to the api");
} else {
    if(!gitlab.mr.reviewers){
        fail("please add some reviewers");
    }
}
```

gitlab version:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/9155770/193462381-f43e06a8-d6c8-4fcf-b47b-4524194be7c7.png">

The Accesstoken has all rights. Do i miss something?
