### DISCUSSION TITLE
Referencing remote dangerfile doesn't work with Typescript

### DISCUSSION THREAD

**Discussion by snowe2010** [danger/danger-js#1359] [Q&A] [answered]
I've tried to consolidate all our dangerfiles to a single one in our shared github actions repo, but I'm getting strange errors. 

First I was getting:

```
Unable to evaluate the Dangerfile
 peril-downloaded-org/pricing-***/dangerfile.ts@tyler/feature/create-reusable-workflows:2
import jiraIssue from "danger-plugin-jira-issue";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at requireFromString (/usr/src/danger/node_modules/require-from-string/index.js:28:4)
    at /usr/src/danger/distribution/runner/runners/inline.js:157:68
    at step (/usr/src/danger/distribution/runner/runners/inline.js:52:23)
    at Object.next (/usr/src/danger/distribution/runner/runners/inline.js:33:53)
    at /usr/src/danger/distribution/runner/runners/inline.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/danger/distribution/runner/runners/inline.js:23:12)
    at runDangerfileEnvironment (/usr/src/danger/distribution/runner/runners/inline.js:118:132)
```

Which didn't make sense to me, because I'm pretty sure those are needed, but anyway, saw [this answer](https://github.com/danger/danger-js/discussions/1153#discussioncomment-1322230) in another discussion so decided to remove all imports, but now I'm getting this error:

```
Unable to evaluate the Dangerfile
 peril-downloaded-org/pricing-***/dangerfile.ts@tyler/feature/create-reusable-workflows:30
  const text: String = fs.readFileSync(f, { encoding: "utf8" });
        ^^^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at requireFromString (/usr/src/danger/node_modules/require-from-string/index.js:28:4)
    at /usr/src/danger/distribution/runner/runners/inline.js:157:68
    at step (/usr/src/danger/distribution/runner/runners/inline.js:52:23)
    at Object.next (/usr/src/danger/distribution/runner/runners/inline.js:33:53)
    at /usr/src/danger/distribution/runner/runners/inline.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/danger/distribution/runner/runners/inline.js:23:12)
    at runDangerfileEnvironment (/usr/src/danger/distribution/runner/runners/inline.js:118:132)
```

which seems to indicate to me that it's not bothering with typescript and trying to use js, though I'm no js expert so I'm not sure if that's correct. I could be totally wrong there. Anyway, what is the expected workflow when trying to use a remote github dangerfile?

Action looks like so:

```
      - name: Danger
        if: ${{ always() }}
        uses: danger/danger-js@11.2.0
        env:
          SPOTLESS_FAILURE: ${{ steps.spotless.conclusion == 'failure' }}
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          args: "--dangerfile org/pricing-github-actions/dangerfile.ts@tyler/feature/create-reusable-workflows"
```

**Comment by orta** [comment]
I bet this is because of the `uses: danger/danger-js@11.2.0` - I'd recommend using Danger like a normal CLI tool which should handle this

**Reply by snowe2010** [reply]
Hm, that will make it a bit more complex to handle in regards to github actions, but I can try it. Does the action not just pull and run it like a cli tool on its own? I'm wondering if there is a way I could contribute a fix here.

**Reply by orta** [reply]
You're welcome to look into it, I added support back when GA was in alpha, and have mainly only had problems from folks since - we dropped it a long time ago, but it largely seems to still work somehow.

**Reply by snowe2010** [reply]
Oh, I didn't realize it wasn't supported anymore. Probably best to switch to just the cli then.

**Reply by snowe2010** [reply]
@orta even using the cli I get the same issues:

```
18s
Run npm install danger danger-plugin-jira-issue

changed 1 package, and audited 141 packages in 962ms

15 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
/home/runner/.asdf/shims/npx
/home/runner/.asdf/shims/npm
Unable to evaluate the Dangerfile
 dangerfile.ts:2
import jiraIssue from "danger-plugin-jira-issue";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at requireFromString (/home/runner/work/document-service/document-service/node_modules/require-from-string/index.js:28:4)
    at /home/runner/work/document-service/document-service/node_modules/danger/distribution/runner/runners/inline.js:157:68
    at step (/home/runner/work/document-service/document-service/node_modules/danger/distribution/runner/runners/inline.js:52:23)
    at Object.next (/home/runner/work/document-service/document-service/node_modules/danger/distribution/runner/runners/inline.js:33:53)
    at /home/runner/work/document-service/document-service/node_modules/danger/distribution/runner/runners/inline.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/document-service/document-service/node_modules/danger/distribution/runner/runners/inline.js:23:12)


Failing the build, there is 1 fail.
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
Feedback: https://github.com/SunRun/document-service/pull/48#issuecomment-1397893399
```

action now looks like this:

```yaml
      - name: Danger
        if: ${{ always() }}
        env:
          SPOTLESS_FAILURE: ${{ steps.spotless.conclusion == 'failure' }}
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          npm install danger danger-plugin-jira-issue
          which npx
          which npm
          npx danger ci
```
