### DISCUSSION TITLE
Is there a recommended setup to avoid duplicated comments?

### DISCUSSION THREAD

**Discussion by sesponda** [danger/danger-js#1429] [Q&A]
We have DangerJS working on Bitbucket Cloud, triggered on every new commit in the PR:
```
image: node:lts
definitions:
  caches:
    node: node_modules
pipelines:
  pull-requests:
    "**":
    - step:
        caches:
        - node
        script:
        - export LANG="C.UTF-8"
        - if [ -z "$DANGER_BITBUCKETCLOUD_REPO_ACCESSTOKEN" ]; then echo "Skipping danger - no authz config available" && exit 0; fi
        - yarn add danger --dev || echo "Skipping Danger - Install error"
        - yarn danger ci || echo "Skipping Danger - Evaluation error"
``` 

... with a rule like this one:

```
function userAccessManagementRules() {
  const changed = danger.git.fileMatch('feature_one/**');

  if (changed) {
    markdown(
      `You have changed Feature One, please check [this](https://example.com)`);
  }
}
```

With this setup, each run will post the same message.
Is this the expected behaviour? Do you have any advice on how to avoid potential noise in PRs, or a different setup?

If DangerJS already provides a way to avoid duplicated messages and I missed it in the docs, sorry. Just point me there.
Otherwise, I'd be curious if others would like this feature. If yes, we could chat about contributing, for example:
* Optional parameter named "unique"=true/false
* Letting the user to specify a comment code that, if present, should be seen only once. 

PS: looking at other pages, it looks like DangerJS should edit the first message, but somehow this is not happening in our case.
