### DISCUSSION TITLE
How is the GitHub action published?

### DISCUSSION THREAD

**Discussion by bertrand-toca** [danger/danger-js#1466] [Q&A]
Perhaps a dumb question, but what's the entry point of `danger/danger-js` when using Danger JS as an action?

i.e. This option in a GitHub workflow
 ```yml
 name: "Danger JS"
 on: [pull_request]
 
 jobs:
   build:
     name: Danger JS
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Danger
       uses: danger/danger-js@9.1.6
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ```
 
According to [GitHub's documentation](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions):
> All actions require a metadata file. The metadata filename must be either action.yml or action.yaml. The data in the metadata file defines the inputs, outputs, and runs configuration for your action.

But there isn't such a file in this repository, so how does it work? I'd like to understand exactly what runs as part of the Danger JS action.

Thank you!
