### DISCUSSION TITLE
Install only TS types?

### DISCUSSION THREAD

**Discussion by antonisprovidakis** [danger/danger-js#1473] [Q&A]
Hello,

Is there a way to install only the TS type definitions?

My use case is that I don't won't to install `danger` as a dependency.
However, I'd like to have code completion and some JSDoc available while writing a Dangerfile.

Specifically, I'm trying to run `danger` on Github Actions, with `npx`:
```
- name: Danger JS
  run: npx danger@12.3.3 ci --failOnErrors
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I guess, it could also be used for the case that is described in the [documentation](https://danger.systems/js/guides/getting_started#:~:text=If%20you%20are%20not%20running%20in%20a%20JavaScript%20ecosystem%2C%20or%20don%27t%20want%20to%20include%20the%20dependency%20then%20you%20can%20use%20Danger%20JS%20as%20an%20action.):
```
- name: Danger
  uses: danger/danger-js@9.1.6
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thank you!
