### ISSUE TITLE
Danger outputs warning but succeeds if using DANGER_GITHUB_API_TOKEN in github actions

### ISSUE THREAD

**Issue by rohit-gohri** [danger/danger-js#1009]
Danger step in github action:

```
    - name: danger
      if: github.event_name == 'pull_request'
      run: |
        yarn danger ci
      env:
        NODE_ENV: test
        CI: 1
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Output:
```
yarn run v1.22.0
$ /home/runner/work/danger-plugin-todos/danger-plugin-todos/node_modules/.bin/danger ci
You need to add GITHUB_TOKEN to your Danger action in the workflow:
  
    - name: Danger JS
      uses: danger/danger-js@X.Y.Z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
You need to add GITHUB_TOKEN to your Danger action in the workflow:
  
    - name: Danger JS
      uses: danger/danger-js@X.Y.Z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead


[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Found only messages, passing those to review.
Feedback: https://github.com/rohit-gohri/danger-plugin-todos/pull/1#issuecomment-595348458
Done in 4.59s.
```

But danger works and is able to comment: https://github.com/rohit-gohri/danger-plugin-todos/pull/1#issuecomment-595348458
