### ISSUE TITLE
Support for Flutter - Dart

### ISSUE THREAD

**Issue by kuyazee** [danger/danger-js#1101]
Are there any plans to add support for Flutter? If not, are there any guides I can use to possibly build this ~~if I can~~

**Comment by orta** [comment]
No plans ( I don't use Flutter) but there's a tutorial on how to make your own Danger language implementation here: https://danger.systems/js/usage/danger-process.html

If you get something up and running ping me and we can talk about getting it into this org and being made more official 👍🏻

**Comment by kuyazee** [comment]
Thank you, I'll study up on this and see what I can do

**Comment by maxlapides** [comment]
We're using Danger with our Flutter project. We're just using the Danger JS. It might be nice in the future to write our Dangerfile in Dart, but it works great today!

And here's our dangerfile.js in full:

```javascript
import { danger, fail, warn } from 'danger'
const readline = require('readline')
const fs = require('fs')
const path = require('path')

class FlutterAnalyzerMessage {
  constructor(message) {
    const found = message.match(/\[(\w+)\] (.+) \((.+):(\d+):(\d+)\)/)
    const baseDir = process.cwd().replace('/danger', '')
    this.type = found[1]
    this.body = found[2]
    this.path = path.relative(baseDir, found[3])
    this.line = found[4]
    this.char = found[5]
  }
}

const flutterAnalysisPath = 'flutter-analyze-log'

if (fs.existsSync(flutterAnalysisPath)) {
  const readInterface = readline.createInterface({
    input: fs.createReadStream(flutterAnalysisPath),
    output: process.stdout,
    console: false,
  })

  readInterface.on('line', (line) => {
    const message = new FlutterAnalyzerMessage(line)
    warn(message.body, message.path, message.line)
  })
}
```

And here's an example GitHub Action that uses Danger:

```yml
name: PR checks

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  analyze:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter analyze --write=danger/flutter-analyze-log
      - uses: actions/setup-node@v2
        if: ${{ failure() }}
        with:
          node-version: '>=16'
      - name: Danger
        if: ${{ failure() }}
        working-directory: danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: npm install && npm run danger-ci
```
