### ISSUE TITLE
[BUG] Github action won't stop load at danger ci command

### ISSUE THREAD

**Issue by mpermperpisang** [danger/danger-js#1175]
Hi, I had a trouble when integrate danger + github action. This is my workflow but somehow it wont't stop loading when try to run danger ci. Could you help me please?

```
name: linter

on:
  - pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Execution
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          yarn install
          yarn danger ci --failOnErrors
```
