### ISSUE TITLE
[BUG] GitHub Action for dangerJs not firing for pull_request_target

### ISSUE THREAD

**Issue by daniel-crouch** [danger/danger-js#1286]
**Describe the bug**

I am fully aware that this is more an issue with GitHub actions rather than DangerJs, but I feel other users have got this working and I can't fathom how.

I have read some articles suggesting that GitHub actions can't be triggered from label events, but this seems hard to believe, and so reaching out to see if this is the case from DangerJs experience.

I'd like to see a GitHub action run DangerJs when a label is added/removed to the PR. My setup looks like this:

```
name: Danger checks 🚧

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'yarn' # Subsequent runs will have the dependencies cached
      - name: Set up azure artifacts auth
        uses: "./.github/actions/azure-artifacts-auth"
        with:
          az-pat: ${{secrets.AZURE_NPM_PAT}}
      - name: Run Danger
        run: |
          npx danger ci --dangerfile ./dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_GITHUB }}
```

**To Reproduce**
1. Add the above GitHub action
2. Add or remove a label

**Expected behavior**
DangerJs script executed via the GitHub action, but nothing happens

**Screenshots**

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.0.7
| node             |  6.15.1
| npm              | 8.1.3
| Operating System | Ubuntu 20.04 LTS

**Additional context**
