### ISSUE TITLE
[BUG] Inline comments often don't show up, or show incorrectly with GitLab self-hosted

### ISSUE THREAD

**Issue by squarefrog** [danger/danger-js#1351]
**Describe the bug**
I'm unable to get inline comments to show up correctly, and consistently, with danger-js and GitLab. While danger correctly adds a comment at the line I'd expect, the comment text is incorrect.

**To Reproduce**
1. Setup a new repo
2. Add the `.gitlab-ci.yml` file listed below
3. Add a test file, `LinterTest.swift` listed below
4. Add the example dangerfile
5. Push up to main
6. Branch off main
7. Edit the `LinterTest.swift`, removing the comments in lines 22-26
8. Push up the change and look at the pipeline for the merge request

<details>
  <summary>.gitlab-ci.yml</summary>

```yaml
stages:
  - analysis

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  FF_ENABLE_JOB_CLEANUP: 'true'

before_script:
  - eval "$(/opt/homebrew/bin/brew shellenv)"
  - brew install danger/tap/danger-js

.mr:
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE=~ /^WIP:/

danger_ci:
  stage: analysis
  extends: .mr
  tags:
    - macos03 # adjust to your setup
  script:
    - echo "Running Danger"
    - DEBUG=* danger ci
  interruptible: true
```
</details>

<details>
  <summary>LinterTest.swift</summary>

  ```swift
  import Foundation

  class LinterTest {
      var a = "ab"

      func annoyLinter() {
          // Triggers swiftformat spaceAroundOperators
          for i in 0 ... 10 {
              print(i)
          } // touch file to check linting

          // Triggers swiftlint empty_count
          _ = a.count == 0
      }

      enum State {
          case unknown
          case loading
          case finished
      }

      //enum NewState {
          //case unknown
          //case loading
          //case finished
      //}
  }
  ```
</details>

<details>
<summary>dangerfile.ts</summary>

```typescript
import { danger } from "danger";

warn("inline warning, line 16", "LinterTest.swift", 16);

warn("global warning")

warn("inline warning, line 22", "LinterTest.swift", 22);

warn("global warning 2, electric boogaloo")
```
</details>

**Expected behavior**
There should be one inline comment, underneath line 22 of `LinterTest.swift`, with the text `inline warning, line 22`. There should be 3 warnings on the main page of the merge request:
* `inline warning, line 16` - as this line isn't part of the changed file, it may not show up at all
* `global warning`
* `global warning 2, electric boogaloo`

**Screenshots**
Overview
<img width="975" alt="Screenshot 2023-01-27 at 15 29 11" src="https://user-images.githubusercontent.com/343450/215124113-b969f28b-ffa3-4611-ab67-cb2d12006fff.png">

Changes tab
<img width="604" alt="Screenshot 2023-01-27 at 15 27 28" src="https://user-images.githubusercontent.com/343450/215123817-5ad27a7c-b9af-47e6-b9e5-e127aeff0395.png">

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          |  11.2.1
| node             | N/A
| npm              | N/A
| Operating System | macOS 12.6.2
| GitLab self-hosted | 15.3
| gitlab-runner | 15.3.0
