### ISSUE TITLE
[BUG] Danger.js removed from Githb PR after merge

### ISSUE THREAD

**Issue by fabiendem** [danger/danger-js#1402]
**Describe the bug**

We noticed that when a PR receives danger.js messages or warnings, after the merge, the Danger.JS comment grouping those is deleted from the PR.
Even if we scroll back in the history of comments on the PR, we can no longer see Danger.js messages.

This is causing issues sometimes when we're discussing on PRs which turn out to be problematic. We would like to point the developer to a Danger.js comment ("we told you so"), but the comment is no longer present.

**To Reproduce**
1. Create a PR
2. Get Danger.JS messages on it
3. Merge the PR
4. Danger.JS comments are no longer present

**Expected behavior**

Danger.JS comments are still present after the merge of the PR.

**Screenshots**

N/A

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.2.1
| node             | 18.15.0
| yarn              | 1.22.19
| Operating System | Ubuntu on CI

**Additional context**

Are we missing some parameter to enable this behavior?

Cheers!

**Comment by fabiendem** [comment]
Thank you, yeah `--newCommment` is too spammy.

> But danger will only delete the comment if it was ran on the CI when the CI run had no issues

We have some checks which will print simple messages and warnings, so which don't mark the PR checks as "failed".

> But danger will only delete the comment if it was ran on the CI when the CI run had no issues, so I'm not sure how you would get a situation where a PR after a merge is running danger but that's likely to do with your CI infra

💡 🚀 I think you just answered my question.
On our repo, we have two sets of Dangers checks, one running while the PR is open and changing, and one running after the merge.
The checks running after the merge are probably deleting the previous messages, because the set of checks is different.
I think we need to make sure the entire set of danger checks runs after the merge as well.

If you're curious, via Github Actions, we run Danger on a PR after a merge using the following code:

```yml
name: Danger JS after merge
on:
  pull_request_target:
    types:
      - closed
env:
  # ......
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -   # ...... steps for setup
      # ....
      - name: Danger after merge
        run: yarn danger ci --dangerfile "./dangerfile_after_merge.ts"
```
