### ISSUE TITLE
[BUG] Github Merge Queue - Danger server stuck in "waiting for status be reported"

### ISSUE THREAD

**Issue by eppisapiafsl** [danger/danger-js#1427]
**Describe the bug**

We have configured "Danger" as a required step in the CI. It works as expected in Pull Request and After the merge process, but we face a problem configuring it for the new GitHub Merge Queue action (Configure to group 3 PRs at time)

**To Reproduce**
1. Configure 2 Danger workflow, one for Pull request and another one for Merge Group
```
name: Danger JS 
# The Merge Queue doesn't populate the PR information, neither the labels
# We need a new DangerJS to pass the CI requirements
on:
    merge_group:
        types:
            - checks_requested

jobs:
  danger_merge_group:
    runs-on: ubuntu-latest
    name: Danger JS
    steps:
      ...
      - name: Danger after merge
        run: yarn danger ci --dangerfile "./dangerfile_merge_group.ts" --id "danger-merge-group" --newComment --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
name: Danger JS
on:
  merge_group:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
env:
  # Github Access Token used to download Github distributed packages such as react-native-wrnch
  # See https://github.com/hinge-health/phoenix#setup-github-access-token
  GITHUB_ACCESS_TOKEN: ${{ secrets.SHARED_PACKAGES_READ }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger JS
    steps:
      ...
      - name: Danger
        run: yarn danger ci --id "Danger" --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

The danger file to run in Merge group is quite simple 😅 
```
import { message } from "danger";


message('PR merged');
```

2. Danger works as expected on Pull request but in the Merge group it get stuck (Even that the CI pass)

| GHA pass | Danger server stuck |
| --- | --- | 
| ![Screenshot 2024-02-26 at 10 03 45 AM](https://github.com/danger/danger-js/assets/82107248/0bc98115-a809-473d-96b4-96292a6c2885)| ![Screenshot 2024-02-26 at 10 03 31 AM](https://github.com/danger/danger-js/assets/82107248/a340eec9-2c2a-465e-b55f-c7c4b53485ee) |

**Expected behavior**

Danger populates the result of the GHA in the Merge Group action.

**Screenshots**

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.3.1
| node             |  20.9.0
| npm              | 0.39.1
| Operating System | Ubuntu

**Additional context**
