### ISSUE TITLE
Feature - Danger Id on the GH Action

### ISSUE THREAD

**Issue by gtkatakura** [danger/danger-js#1464]
I am using danger to create an reusable workflow to do some common validations across multiple repositories. It works great. The problem is that some repositories already has the dangerfile configured and the both the workflows (the reusable workflow and the specific workflow from the repository) are overrinding the same comment. Would be nice to have the ability to pass the --id for the github action.

```yaml
      - name: Run Danger
        uses: danger/danger-js@12.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: my-custom-id
```
