### ISSUE TITLE
Danger failed to run dangerfile.ts in GitHub Action, but still passed check

### ISSUE THREAD

**Issue by daihovey** [danger/danger-js#986]
Running action in PR (React Native project); it's passing, but errors show its failing inside `dangerfile.ts`

GitHub Action:
```
name: Pull Request Review
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code...
      uses: actions/checkout@v2
    - name: Get Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: install yarn
      run: npm install -g yarn
    - name: yarn install
      run: | 
        yarn install --frozen-lockfile 
    - run: yarn test
      env:
        CI: true
    - run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Output:
```
Run yarn danger ci
yarn run v1.22.0
$ /home/runner/work/mobile-app/mobile-app/node_modules/.bin/danger ci
Unable to evaluate the Dangerfile
 TypeError: Cannot read property 'join' of 
    at Object.<anonymous> (dangerfile.ts:3:46)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.requireFromString [as default] (/home/runner/work/mobile-app/mobile-app/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at exports.runDangerfileEnvironment (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:105:136)


Danger: ⅹ Failing the build, there is 1 fail.
## Failures
## Failures
Danger failed to run `dangerfile.ts`.
## Markdowns
## Error TypeError
Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at Object.<anonymous> (dangerfile.ts:3:46)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.requireFromString [as default] (/home/runner/work/mobile-app/mobile-app/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at exports.runDangerfileEnvironment (/home/runner/work/mobile-app/mobile-app/node_modules/danger/distribution/runner/runners/inline.js:105:136)
### Dangerfile

1| // Removed import {message, danger} from "danger"
2| 
-----------------------------------------------^
3| const modifiedMD = danger.git.modified_files.join("- ")
4| message("Changed Files in this PR: \n - " + modifiedMD)

```

<img width="249" alt="Screen Shot 2020-02-07 at 12 36 51 pm" src="https://user-images.githubusercontent.com/47039937/73993544-8e5bc880-49a6-11ea-82e3-9b4130cea8d1.png">
