### ISSUE TITLE
Should Danger work on GitHub Issues as well?

### ISSUE THREAD

**Issue by mokagio** [danger/danger-js#999]
**Background**: I'm trying to migrate from a Peril setup to Danger running on GitHub Action. [It makes sense](https://github.com/danger/peril#peril-vs-github-actions).

The docs imply Danger should be able to run fine when called from a GitHub Action triggered not from an even other than PR, see [this](https://github.com/danger/danger-js/blob/master/CHANGELOG.md#500) and [this](https://github.com/mokagio/danger-js/blob/master/source/dsl/DangerDSL.ts#L117-L119). But, when I run `yarn run danger ci` from a GitHub workflow build triggered by an `on: issue` event, it fails.

The failure I'm getting is a 404, Danger seems to be hitting the GitHub API for pull requests but this is an issue.

The GitHub Action build is [here](https://github.com/mokagio/danger-js-github-action-playground/runs/454425076?check_suite_focus=true#step:7:11).

<img width="1170" alt="Screen Shot 2020-02-19 at 15 11 37" src="https://user-images.githubusercontent.com/1218433/74801254-299b5900-532a-11ea-8427-fadf22576fd4.png">

My workflow is [here](https://github.com/mokagio/danger-js-github-action-playground/blob/0e5c74b51da6c2bdeaa8d40777edcb1739d11733/.github/workflows/check-issue-labels.yml):

```yml
name: Validate Issue Labels
on:
  issues:
    types: [opened, labeled, unlabeled]
     
     ...

    - name: Validate
      run: |
        yarn run danger ci \
          --dangerfile dangerfiles/check-label-on-issue.ts
          --id issue_label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

To try and work around this, I checked out https://github.com/danger/danger-js/ locally, and changed [the code that generates the URL Danger uses for that first 404ing request](https://github.com/mokagio/danger-js/blob/d4210479f6a353c52c76dcf219ac35168829d3b1/source/platforms/github/GitHubAPI.ts#L200) from "`pull`" to "`issues`", it got the data all right, but then failed later down the track. I wasn't too surprised by that, but it was worth a shot.
